export { default as MyProfile } from './MyProfile/MyProfile'
export { default as SearchCourse } from './SearchCourse/SearchCourse'
export { default as SignInUp } from './AuthPages/SignInUp'
export { default as SignIn } from './AuthPages/SignIn'
export { default as SignUp } from './AuthPages/SignUp'
export { default as InfoForm } from './AuthPages/InfoForm'
export { default as CourseForm } from './AuthPages/CourseForm'
export { default as SearchComp } from './AuthPages/SearchComp'

export { default as ChatBox } from './ChatBox/Chatbox'