export { default as MyProfile } from './MyProfile/MyProfile'
export { default as SearchCourse } from './SearchCourse/SearchCourse'
export { default as SignInUp } from './AuthPages/SignInUp'
export { default as SignIn } from './AuthPages/SignIn'
export { default as SignUp } from './AuthPages/SignUp'